CREATE TABLE IF NOT EXISTS "tecnico" ("id_tecnico" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "razon_social" TEXT NOT NULL  UNIQUE , "habilitado" BOOL NOT NULL  DEFAULT 0, "fecha_ingreso" DATETIME );
CREATE TABLE IF NOT EXISTS "tipo_operacion_orden_trabajo" ( "id_tipo_operacion_orden_trabajo" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "nombre" TEXT NOT NULL UNIQUE );
CREATE TABLE IF NOT EXISTS "equipamiento" ( "id_equipamiento" INTEGER PRIMARY KEY  NOT NULL ,"descripcion" TEXT NOT NULL ,"marca" TEXT DEFAULT (NULL) ,"modelo" TEXT DEFAULT (NULL) ,"numero_serie" TEXT DEFAULT (NULL) ,"fecha_compra" TEXT DEFAULT (NULL) ,"fecha_vencimiento" TEXT DEFAULT (NULL) ,"id_factura_compra" INTEGER DEFAULT (NULL) , "id_cliente" INTEGER NOT NULL  DEFAULT 0, "cantidad_elementos" INTEGER NOT NULL  DEFAULT 1, "fecha_baja" DATETIME, "razon_baja" TEXT, "observaciones" TEXT DEFAULT NULL);
CREATE TABLE IF NOT EXISTS "operacion_orden_trabajo" ("id_operacion" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "id_orden_trabajo" INTEGER NOT NULL , "fecha_hora" DATETIME NOT NULL  DEFAULT CURRENT_TIMESTAMP, "descripcion" TEXT NOT NULL , "tipo_operacion" INTEGER NOT NULL , "id_tecnico" INTEGER NOT NULL , "costo" DOUBLE NOT NULL  DEFAULT 0.0 );
CREATE TABLE IF NOT EXISTS "orden_trabajo" ( "id_orden_trabajo" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "cliente_id" INTEGER NOT NULL  DEFAULT 0, "fecha_ingreso" DATETIME NOT NULL  DEFAULT CURRENT_TIMESTAMP, "requerente" TEXT NOT NULL , "ingresante" TEXT NOT NULL , "fecha_vencimiento" DATETIME NOT NULL , "fecha_devolucion" DATETIME, "id_equipamiento" INTEGER NOT NULL , "id_factura" INTEGER, "id_tecnico" INTEGER NOT NULL, "causa_ingreso" TEXT NOT NULL );
INSERT OR IGNORE INTO "sqlite_sequence" ( "name", "seq" ) VALUES ( 'tecnico', '1' );
INSERT OR IGNORE INTO "sqlite_sequence" ( "name", "seq" ) VALUES ( 'tipo_operacion_orden_trabajo', '1' );
INSERT OR IGNORE INTO "sqlite_sequence" ( "name", "seq" ) VALUES ( 'equipamiento', '1' );
INSERT OR IGNORE INTO "sqlite_sequence" ( "name", "seq" ) VALUES ( 'operacion_orden_trabajo', '1' );
INSERT OR IGNORE INTO "sqlite_sequence" ( "name", "seq" ) VALUES ( 'orden_trabajo', '1' );
INSERT OR IGNORE INTO "tipo_operacion_orden_trabajo" VALUES ( 1, "Cambio de Técnico" );
INSERT OR IGNORE INTO "tipo_operacion_orden_trabajo" VALUES ( 2, "Cambio de Cliente" );
INSERT OR IGNORE INTO "tipo_operacion_orden_trabajo" VALUES ( 3, "Cambio de Equipamiento" );
INSERT OR IGNORE INTO "tipo_operacion_orden_trabajo" VALUES ( 4, "Cierre de orden" );
INSERT OR IGNORE INTO "tipo_operacion_orden_trabajo" VALUES ( 5, "Devolución al cliente" );
INSERT OR IGNORE INTO "tipo_operacion_orden_trabajo" VALUES ( 6, "Cancelación de la orden" );
INSERT OR IGNORE INTO "tipo_operacion_orden_trabajo" VALUES ( 7, "Facturacion de item de orden" );
INSERT OR IGNORE INTO "tipo_operacion_orden_trabajo" VALUES ( 8, "Ingreso al taller" );
CREATE VIEW IF NOT EXISTS "v_equipamiento" AS SELECT e.id_equipamiento AS id_equipamiento, e.numero_serie as numero_serie, e.descripcion as descripcion, c.id as id_cliente, c.razon_social as razon_social, e.cantidad_elementos as cantidad_elementos, e.fecha_compra as fecha_compra, e.fecha_baja as fecha_baja FROM equipamiento AS e INNER JOIN clientes AS c ON e.id_cliente = c.id;