#ifndef COMPROBANTES_GLOBAL_H
#define COMPROBANTES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMPROBANTES_LIBRARY)
#  define COMPROBANTESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMPROBANTESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMPROBANTES_GLOBAL_H
