language: cpp

compiler: gcc

install:
    - sudo pip install cpp-coveralls
    - sudo apt-get install libqt4-sql-sqlite
    - cp bin/travis.pri travis.pri
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

script:  
    - qmake gestotux.pro
    - make
    - cd test/PreferenciasTest
    - ./tst_preferenciastest
    - cd ../ProductosTest
    - ./tst_productostest
    - cd ../EquipamientosTest
    - ./tst_equipamientos
    - cd ../ECBProductosTest
    - ./tst_ecbproductostest
    - cd ../PeriodoServicioTest
    - ./tst_periodoserviciotest
    - cd ../ComprasTest
    - ./tst_comprastest
    - cd ../ProveedorTest
    - ./tst_proveedortest
    - cd ../VentasTest
    - ./tst_ventastest

after_success:
    - coveralls --exclude-pattern ".*automoc\.cpp" --exclude-pattern ".*\.moc" --exclude-pattern "/opt/.*" --exclude-pattern "/usr/.*" --exclude-pattern ".*moc_.*" --exclude-pattern ".*ui_.*" --exclude-pattern ".*qrc_.*" --exclude-pattern "tst_*" --exclude lib --exclude tests

notifications:
  email: false