language: cpp

compiler: gcc

install:
    - sudo pip install cpp-coveralls

script:  
    - qmake "LIBS += -gcov QMAKE_CXXFLAGS += -g -Wall -fprofile-arcs -ftest-coverage -O0 QMAKE_LFLAGS += -g -Wall -fprofile-arcs -ftest-coverage -O0" gestotux.pro
    - make

after_success:
    - coveralls --exclude lib --exclude tests
