language: cpp

compiler: gcc

install:
    - sudo pip install cpp-coveralls
    - cp bin/travis.pri travis.pri
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

script:  
    - qmake gestotux.pro
    - make
    - cd test/PreferenciasTest
    - ./tst_preferenciastest
    - cd ../ProductosTest
    - ./tst_productostest
    - cd ../PeriodoServicioTest
    - ./tst_periodoserviciotest
    - cd ../EquipamientosTest
    - ./tst_equipamientotest

after_success:
    - coveralls --exclude-pattern ".*automoc\.cpp" --exclude-pattern ".*\.moc" --exclude-pattern "/opt/.*" --exclude-pattern "/usr/.*" --exclude-pattern ".*moc_.*" --exclude-pattern ".*ui_.*" --exclude-pattern ".*qrc_.*" --exclude lib --exclude tests
