language: cpp

compiler: gcc

install:
    - sudo pip install cpp-coveralls
    - cp bin/travis.pri travis.pri

script:  
    - qmake gestotux.pro
    - make

after_success:
    - coveralls --exclude lib --exclude tests
