CREATE TABLE IF NOT EXISTS compras ( id INTEGER PRIMARY KEY AUTOINCREMENT,id_proveedor NUMERIC NOT NULL, fecha TEXT NOT NULL, total NUMERIC NOT NULL, id_caja NUMERIC NULL, "contado" BOOL NOT NULL  DEFAULT 1 );
INSERT OR IGNORE INTO compras VALUES ( 1, 1, "2014-01-01", 100, null, 0 );
INSERT OR IGNORE INTO compras VALUES ( 2, 2, "2014-02-01", 200, null, 0 );