CREATE TABLE IF NOT EXISTS provincias ( "id_provincia" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "nombre" TEXT NOT NULL , "id_pais" INTEGER NOT NULL );
INSERT INTO `provincias` VALUES ( 168, 'Buenos Aires',  13 );
INSERT INTO `provincias` VALUES ( 169, 'Catamarca',  13 );
INSERT INTO `provincias` VALUES ( 170, 'Chaco',  13 );
INSERT INTO `provincias` VALUES ( 171, 'Chubut',  13 );
INSERT INTO `provincias` VALUES ( 172, 'Cordoba',  13 );
INSERT INTO `provincias` VALUES ( 173, 'Corrientes',  13 );
INSERT INTO `provincias` VALUES ( 174, 'Distrito Federal',  13 );
INSERT INTO `provincias` VALUES ( 175, 'Entre Rios',  13 );
INSERT INTO `provincias` VALUES ( 176, 'Formosa',  13 );
INSERT INTO `provincias` VALUES ( 177, 'Jujuy',  13 );
INSERT INTO `provincias` VALUES ( 178, 'La Pampa',  13 );
INSERT INTO `provincias` VALUES ( 179, 'La Rioja',  13 );
INSERT INTO `provincias` VALUES ( 180, 'Mendoza',  13 );
INSERT INTO `provincias` VALUES ( 181, 'Misiones',  13 );
INSERT INTO `provincias` VALUES ( 182, 'Neuquen',  13 );
INSERT INTO `provincias` VALUES ( 183, 'Rio Negro',  13 );
INSERT INTO `provincias` VALUES ( 184, 'Salta',  13 );
INSERT INTO `provincias` VALUES ( 185, 'San Juan',  13 );
INSERT INTO `provincias` VALUES ( 186, 'San Luis',  13 );
INSERT INTO `provincias` VALUES ( 187, 'Santa Cruz',  13 );
INSERT INTO `provincias` VALUES ( 188, 'Santa Fe',  13 );
INSERT INTO `provincias` VALUES ( 189, 'Santiago del Estero',  13 );
INSERT INTO `provincias` VALUES ( 190, 'Tierra del Fuego',  13 );
INSERT INTO `provincias` VALUES ( 191, 'Tucuman',  13 );